// Real Halo character meshes for the agent renderer. Data comes from
// game/characters-data.js (generated by scripts/convert-h3-assets.mjs from
// H3EK source art — Halo 2 marines/civilians/infection form, Halo 3 flood
// combat forms; see assets/NOTICE.txt). Each model is a small set of
// texture groups; the renderer draws one InstancedMesh per group.

import * as THREE from './vendor/three.module.js';
import { CHARACTERS } from './characters-data.js';

const texLoader = new THREE.TextureLoader();
const texCache = {};
const texFor = (name) => {
  if (!texCache[name]) {
    const t = texLoader.load(`./assets/characters/${name}.png`);
    t.colorSpace = THREE.SRGBColorSpace;
    texCache[name] = t;
  }
  return texCache[name];
};

// [{ geometry, texture }] per model — geometry is meters, y-up, +X-forward,
// feet at y=0 (rotate with the same heading convention as the carry rifle)
export const characterParts = (name) => CHARACTERS[name].groups.map((g) => {
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(g.pos, 3));
  geo.setAttribute('normal', new THREE.Float32BufferAttribute(g.norm, 3));
  geo.setAttribute('uv', new THREE.Float32BufferAttribute(g.uv, 2));
  geo.setIndex(g.idx);
  return { geometry: geo, texture: texFor(g.tex) };
});
